POST http://elastic:changeme@localhost:9200/_security/user/elastic/_password
Content-Type: application/json

{
  "password": "elastic"
}

###
POST http://elastic:elastic@localhost:9200/_security/user/kibana_system/_password
Content-Type: application/json

{
"password": "kibana"
}


###
POST http://elastic:elastic@localhost:9200/_security/user/logstash_system/_password
Content-Type: application/json

{
"password": "logstash"
}

###

# Create index
PUT http://elastic:elastic@localhost:9200/synthetics
###
PUT http://elastic:elastic@localhost:9200/metrics

###
POST http://elastic:elastic@localhost:9200/_security/role/logstash_writer
Content-Type: application/json

{
  "cluster": [
    "manage_index_templates",
    "monitor",
    "manage_ilm"
  ],
  "indices": [
    {
      "names": [
        "logs-generic-default",
        "logstash-*",
        "ecs-logstash-*",
        "metrics",
        "synthetics",
        "logs"
      ],
      "privileges": [
        "write",
        "create",
        "create_index",
        "manage",
        "manage_ilm"
      ]
    },
    {
      "names": [
        "logstash",
        "ecs-logstash"
      ],
      "privileges": [
        "write",
        "manage"
      ]
    }
  ]
}

###
POST http://elastic:elastic@localhost:9200/_security/user/logstash/
Content-Type: application/json

{
  "password": "logstash",
  "roles" : [ "logstash_writer" ]
}